import { describe, expect, it } from "vitest";
import { Solar } from "lunar-typescript";
import { cast } from "../src/core";
import { solarClock } from "../src/core/calendar";

describe("calendar and the separation of physical instant from clock", () => {
  it("changes day at 23:00 while midnight remains in the same sexagenary day", () => {
    const before = cast({
      datetime: "2026-09-22T22:59:59",
      timeBasis: "standard",
    });
    const after = cast({
      datetime: "2026-09-22T23:00:00",
      timeBasis: "standard",
    });
    const midnight = cast({
      datetime: "2026-09-23T00:00:00",
      timeBasis: "standard",
    });
    // HKO September 2026, visually read date cells 22 (己亥), 23 (庚子).
    // https://www.hko.gov.hk/en/gts/astron2026/files/2026cal09.pdf
    // HKO supplies civil-date names; moving that name at 23:00 is our explicit
    // sect convention, not a claim that HKO endorses that divination day boundary.
    expect(before.day).toEqual({ stem: "己", branch: "亥" });
    expect(after.day).toEqual({ stem: "庚", branch: "子" });
    expect(after.day).toEqual(midnight.day);
    expect(before.hourBranch).toBe("亥");
    expect(after.hourBranch).toBe("子");
    expect(after.time!.utcIso).toBe("2026-09-22T15:00:00.000Z");
  });
  it("matches independently read HKO date names across the Gregorian year boundary", () => {
    // Original single-page calendars, cells Dec 31 and Jan 1–2, viewed 2026-09-23:
    // https://www.hko.gov.hk/en/gts/astron2025/files/2025cal12.pdf
    // https://www.hko.gov.hk/en/gts/astron2026/files/2026cal01.pdf
    const c = (datetime: string) => cast({ datetime, timeBasis: "standard" });
    expect(c("2025-12-31T12:00:00").day).toEqual({ stem: "甲", branch: "戌" });
    expect(c("2026-01-01T12:00:00").day).toEqual({ stem: "乙", branch: "亥" });
    expect(c("2026-01-02T12:00:00").day).toEqual({ stem: "丙", branch: "子" });
    expect(c("2025-12-31T22:59:59").day).toEqual({ stem: "甲", branch: "戌" });
    expect(c("2025-12-31T23:00:00").day).toEqual({ stem: "乙", branch: "亥" });
    // December solstice remains the latest major term into January.
    for (const date of ["2025-12-31T12:00:00", "2026-01-01T12:00:00"]) {
      expect(c(date).monthGeneral).toBe("丑");
      expect(c(date).monthBranch).toBe("子");
    }
  });
  it.each([
    // Fixed published HKT minutes, NOT dates generated by lunar-typescript.
    // HKO December 2025 / January 2026 / September 2026 monthly calendar sidebars.
    ["2025-12-21T23:02:00", "2025-12-21T23:04:00", "寅", "丑", "子", "子"],
    ["2026-01-05T16:22:00", "2026-01-05T16:24:00", "丑", "丑", "子", "丑"],
    ["2026-01-20T09:44:00", "2026-01-20T09:46:00", "丑", "子", "丑", "丑"],
    ["2026-09-07T22:40:00", "2026-09-07T22:42:00", "巳", "巳", "申", "酉"],
    ["2026-09-23T08:04:00", "2026-09-23T08:06:00", "巳", "辰", "酉", "酉"],
  ] as const)(
    "separates major-term generals from minor-term months around %s",
    (before, after, oldGeneral, newGeneral, oldMonth, newMonth) => {
      // ±1 minute respects the official table's minute precision. Testing at a
      // library-computed second is retained below as a separate internal check.
      for (const longitude of [-179, 75, 120, 179]) {
        const a = cast({ datetime: before, timeBasis: "solar", longitude });
        const b = cast({ datetime: after, timeBasis: "solar", longitude });
        expect([a.monthGeneral, b.monthGeneral]).toEqual([
          oldGeneral,
          newGeneral,
        ]);
        expect([a.monthBranch, b.monthBranch]).toEqual([oldMonth, newMonth]);
      }
    },
  );
  it.each([
    ["2026-01-01", "12:03:24"],
    ["2026-02-11", "12:14:11"],
    ["2026-09-22", "11:52:49"],
    ["2026-09-23", "11:52:28"],
    ["2026-11-04", "11:43:33"],
    ["2026-12-31", "12:02:49"],
  ])(
    "matches CWA's independently tabulated solar transit at 120E on %s",
    (date, transit) => {
      // CWA 2026 sun-transit table, one page, named row/month cells visually checked.
      // https://www.cwa.gov.tw/Data/astronomy/2026suntr.pdf
      // Header specifies standard time of transit across the 120E meridian.
      // At transit, apparent solar time is 12:00. Allow 5s for published rounding
      // and independent astronomical model differences; no sub-second claim.
      const utc = new Date(`${date}T${transit}+08:00`);
      const apparent = solarClock(utc, 120);
      expect(
        Math.abs(apparent.civil.getTime() - Date.parse(`${date}T12:00:00Z`)),
      ).toBeLessThanOrEqual(5000);
    },
  );
  it("uses official day names and solar-transit bounds when apparent time crosses midnight and New Year", () => {
    // CWA Sep22/23 transits imply EOT +7m11s/+7m32s. Around the intervening
    // midnight, use that 21s envelope (plus 2s), not a made-up exact EOT.
    const midnight = cast({
      datetime: "2026-09-22T23:55:00",
      timeBasis: "solar",
      longitude: 120,
    });
    const midnightMs = Date.parse(
      midnight.time!.selected.replace(" ", "T") + "Z",
    );
    expect(midnightMs).toBeGreaterThanOrEqual(
      Date.parse("2026-09-23T00:02:09Z"),
    );
    expect(midnightMs).toBeLessThanOrEqual(Date.parse("2026-09-23T00:02:34Z"));
    expect(midnight.day).toEqual({ stem: "庚", branch: "子" });
    // At 22:55 the solar clock has already passed the configured 23:00 boundary.
    const early = cast({
      datetime: "2026-09-22T22:55:00",
      timeBasis: "solar",
      longitude: 120,
    });
    expect(early.day).toEqual({ stem: "庚", branch: "子" });
    expect(
      cast({ datetime: "2026-09-22T22:55:00", timeBasis: "standard" }).day,
    ).toEqual({ stem: "己", branch: "亥" });
    // CWA Dec31 2025 12:02:56 / Jan1 2026 12:03:24 give EOT -176/-204 seconds.
    // https://www.cwa.gov.tw/Data/astronomy/2025suntr.pdf (Dec31 row)
    const newYear = cast({
      datetime: "2026-01-01T01:00:00",
      timeBasis: "solar",
      longitude: 75,
    });
    const selectedMs = Date.parse(
      newYear.time!.selected.replace(" ", "T") + "Z",
    );
    expect(selectedMs).toBeGreaterThanOrEqual(
      Date.parse("2025-12-31T21:56:34Z"),
    );
    expect(selectedMs).toBeLessThanOrEqual(Date.parse("2025-12-31T21:57:06Z"));
    expect(newYear.day).toEqual({ stem: "甲", branch: "戌" });
    expect(newYear.hourBranch).toBe("亥");
    expect(newYear.monthGeneral).toBe("丑");
    expect(
      cast({ datetime: "2026-01-01T01:00:00", timeBasis: "standard" }).day,
    ).toEqual({ stem: "乙", branch: "亥" });
  });
  it("uses exactly the frozen 卯申 / 酉寅 daylight boundary", () => {
    const c = (datetime: string) => cast({ datetime, timeBasis: "standard" });
    expect(c("2026-09-23T04:59:59").daytime).toBe(false);
    expect(c("2026-09-23T05:00:00").daytime).toBe(true);
    expect(c("2026-09-23T16:59:59").daytime).toBe(true);
    expect(c("2026-09-23T17:00:00").daytime).toBe(false);
  });
  it("matches HKO 2026 equinox timing to the published minute precision", () => {
    // HKO Almanac 2026: spring equinox 20 March, 22:46 HKT.
    // https://www.hko.gov.hk/tc/gts/astron2026/files/HKO_almanac_2026.pdf
    const terms = Solar.fromYmd(2026, 3, 20).getLunar().getJieQiTable();
    const computed = Date.parse(
      terms["春分"].toYmdHms().replace(" ", "T") + "Z",
    );
    expect(
      Math.abs(computed - Date.parse("2026-03-20T22:46:00Z")),
    ).toBeLessThanOrEqual(30_000);
    expect(
      cast({ datetime: "2026-03-20T22:45:00", timeBasis: "standard" })
        .monthGeneral,
    ).toBe("亥");
    expect(
      cast({ datetime: "2026-03-20T22:47:00", timeBasis: "standard" })
        .monthGeneral,
    ).toBe("戌");
  });
  it("crosses the numerical term at its actual instant, even when solar time is on another hour/date", () => {
    const term = Solar.fromYmd(2026, 9, 23).getLunar().getJieQiTable()["秋分"];
    const at = term.toYmdHms().replace(" ", "T");
    const pseudo = new Date(at + "Z");
    const before = new Date(pseudo.getTime() - 1000).toISOString().slice(0, 19);
    for (const longitude of [-179, 0, 75, 120, 179]) {
      const a = cast({ datetime: before, timeBasis: "solar", longitude });
      const b = cast({ datetime: at, timeBasis: "solar", longitude });
      const standard = cast({ datetime: at, timeBasis: "standard" });
      expect(a.monthGeneral).toBe("巳");
      expect(b.monthGeneral).toBe("辰");
      expect(b.monthGeneral).toBe(standard.monthGeneral);
      expect(b.monthBranch).toBe(standard.monthBranch);
      expect(b.time!.utcIso).toBe(standard.time!.utcIso);
    }
  });
  it("has continuous solar dates near the international date line", () => {
    const utc = new Date("2026-09-22T16:00:00Z");
    const west = solarClock(utc, -179),
      east = solarClock(utc, 179);
    expect(west.civil.toISOString().slice(0, 10)).toBe("2026-09-22");
    expect(east.civil.toISOString().slice(0, 10)).toBe("2026-09-23");
    expect((east.civil.getTime() - west.civil.getTime()) / 60000).toBeCloseTo(
      358 * 4,
      1,
    );
    expect(Math.abs(west.equationMinutes)).toBeLessThan(20);
    expect(Math.abs(east.equationMinutes)).toBeLessThan(20);
  });
  it("unrolls midnight without a 24-hour jump at the solar-clock wrap", () => {
    let previous = solarClock(
      new Date("2026-09-22T15:40:00Z"),
      120,
    ).civil.getTime();
    for (let minute = 1; minute <= 40; minute++) {
      const next = solarClock(
        new Date(Date.parse("2026-09-22T15:40:00Z") + minute * 60000),
        120,
      ).civil.getTime();
      expect(next - previous).toBeGreaterThan(59900);
      expect(next - previous).toBeLessThan(60100);
      previous = next;
    }
  });
  it("matches the independent NOAA equation-of-time approximation within 75 seconds over the year", () => {
    // NOAA fractional-year approximation, independent of Astronomy Engine.
    // https://gml.noaa.gov/grad/solcalc/solareqns.PDF
    // This is a coarse cross-check, not a sub-second accuracy certificate.
    for (let month = 0; month < 12; month++) {
      const utc = new Date(Date.UTC(2026, month, 15, 12));
      const day = 1 + (utc.getTime() - Date.UTC(2026, 0, 1, 12)) / 86400000;
      const gamma = ((2 * Math.PI) / 365) * (day - 1);
      const eot =
        229.18 *
        (0.000075 +
          0.001868 * Math.cos(gamma) -
          0.032077 * Math.sin(gamma) -
          0.014615 * Math.cos(2 * gamma) -
          0.040849 * Math.sin(2 * gamma));
      expect(Math.abs(solarClock(utc, 0).equationMinutes - eot)).toBeLessThan(
        1.25,
      );
    }
  });
  it("solar and standard basis genuinely produce different charts near a relevant boundary", () => {
    const input = { datetime: "2026-09-23T06:00:00", longitude: 75 };
    const a = cast({ ...input, timeBasis: "solar" }),
      b = cast({ ...input, timeBasis: "standard" });
    expect(a.hourBranch).not.toBe(b.hourBranch);
    expect(a.daytime).not.toBe(b.daytime);
    expect(a.heavenPlate).not.toEqual(b.heavenPlate);
    expect(a.monthGeneral).toBe(b.monthGeneral);
  });
  it("boundary warnings cover actual term and selected-clock boundaries", () => {
    expect(
      cast({ datetime: "2026-09-23T05:01:00", timeBasis: "standard" }).time!
        .nearBoundary,
    ).toBe(true);
    expect(
      cast({ datetime: "2026-09-23T05:30:00", timeBasis: "standard" }).time!
        .nearBoundary,
    ).toBe(false);
  });
});
